### Internal User  — 201
POST http://localhost:8081/api/auth/internal/user
Content-Type: application/json
// Написать новый telegram_user_id для успешного импорта нового пользователя вместе с его ролями

{
  "telegram_user_id": 644040130335,
  "roles": ["ADMIN","STUDENT"]
}
###

### Internal User  — 200
POST http://localhost:8081/api/auth/internal/user
Content-Type: application/json
// Написать  telegram_user_id уже существующего пользователя для обновления ролей

{
  "telegram_user_id": 6440401305,
  "roles": ["ADMIN","STUDENT"]
}
###

### Internal User  — 400 Bad Request
POST http://localhost:8081/api/auth/internal/user
Content-Type: application/json

{
  "telegram_user_id": 628570952,
  "roles": ["ADMIN", "UNKNOWN_ROLE"]
}
###

### Internal User  — 400 Not Null
POST http://localhost:8081/api/auth/internal/user
Content-Type: application/json

{
  "telegram_user_id": null ,
  "roles": []
}
###


### Iternal Users - 200 OK
GET http://localhost:8081/api/auth/internal/users?telegram_user_ids=1,2,3
Content-Type: application/json
###

### Iternal Users - 400 telegram_user_ids must not contain nulls
GET http://localhost:8081/api/auth/internal/users?telegram_user_ids=1,,2
Content-Type: application/json
###

### Iternal Users - 400 telegram_user_ids must not be empty
GET http://localhost:8081/api/auth/internal/users?telegram_user_ids=
Content-Type: application/json
###

### Iternal Users - 400 telegram_user_ids must be positive
GET http://localhost:8081/api/auth/internal/users?telegram_user_ids=-1
Content-Type: application/json
###

### Iternal Users - 400 parameter is missing: telegram_user_ids
GET http://localhost:8081/api/auth/internal/users
Content-Type: application/json
###

### Iternal Users - 400 Invalid parameter type
GET http://localhost:8081/api/auth/internal/users?telegram_user_ids=a
Content-Type: application/json
###


