package com.itmentorcommunityplatform.authservice.docs.auth;


import com.itmentorcommunityplatform.authservice.advice.ErrorResponseDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Operation(
        summary = "Authenticate user via Telegram",
        description = """
                ### How to test this endpoint

                For successful authentication you must use **initData generated by your Telegram bot**.  
                Use the bot token of the Telegram bot configured in your backend — Telegram will generate a valid `initData` string only for this bot.

                ### Example of initData (JSON-like debug format)

                ```text
                user=%7B%22id%22%3A628570951%2C%22first_name%22%3A%22llqq%22...
                ```

                Replace this value with the real initData from Telegram WebApp.
                """,
        requestBody = @RequestBody(
                required = true,
                content = @Content(
                        mediaType = "text/plain",
                        examples = {
                                @ExampleObject(
                                        name = "Valid initData example",
                                        value = "<PASTE_YOUR_INITDATA_HERE>"
                                )
                        }
                )
        )
)
@ApiResponses({
        @ApiResponse(responseCode = "200", description = "Authentication successful. JWT returned in Authorization header."),
        @ApiResponse(responseCode = "400", description = "Invalid initData format",
                content = @Content(schema = @Schema(implementation = ErrorResponseDto.class))),
        @ApiResponse(responseCode = "401", description = "Unauthorized",
                content = @Content(schema = @Schema(implementation = ErrorResponseDto.class))),
        @ApiResponse(responseCode = "500", description = "Internal server error",
                content = @Content(schema = @Schema(implementation = ErrorResponseDto.class)))
})
public @interface AuthControllerDocs {
}
