spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
      properties:
        max.block.ms: 30000
        request.timeout.ms: 10000
        delivery.timeout.ms: 30000
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000
        linger.ms: 5

kafka:
  topic:
    auth-user-created: auth.user.created
    auth-user-authenticated: auth.user.authenticated

telegram:
  init-data-expiration-seconds: 1800
  bot-token: ${TELEGRAM_BOT_TOKEN}
  admins: 197342870,6926659633,107541084

jwt:
  expiration_minutes: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

validate-telegram-initdata-timestamp: true