spring:
  datasource:
    url: jdbc:postgresql://database:5432/it_mentor_community_platform?currentSchema=auth_service
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:password}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

kafka:
  topic:
    auth-user-created: auth.user.created

jwt:
  secret: 632eca39fc29068edc74133ca9cf8f40b4942191f80c0c78dd588835beb5f57b