spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    auth-user-created: auth.user.created

telegram:
  init-data-expiration-seconds: 1800
  bot-token: ${TELEGRAM_BOT_TOKEN}
  admins: 197342870,6926659633,107541084

jwt:
  expiration_minutes: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus