spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
