spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/it_mentor_community_platform
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml



telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:open test token}
  init-data-expiration-seconds: 1800
jwt:
  secret: ${JWT_SECRET}
  expiration_minutes: 30
